framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: session.handler.redis
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

services:
    session.handler.redis:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@Redis'  # Utilisation directe de l'objet Redis

    # Définition du service Redis pour la connexion
    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                  - '%env(REDIS_HOST)%'  # Assurez-vous que cette variable est définie dans votre .env
                  - '%env(int:REDIS_PORT)%'  # Utilisation de la conversion de type pour le port

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
