services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/cleanthis:cached
    mem_limit: 4g
    cpus: 2.5

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/cleanthis:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cleanthis
      MYSQL_USER: cleanthis_user
      MYSQL_PASSWORD: cleanthis_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    cpus: 2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - database

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mail_data:/data

volumes:
  db_data:
  cleanthis:
  mail_data: