<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'is_confirmed' => [parent::class, 'is_confirmed', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'ope_employe' => [parent::class, 'ope_employe', null],
        "\0".parent::class."\0".'operations' => [parent::class, 'operations', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'street' => [parent::class, 'street', null],
        "\0".parent::class."\0".'zipcode' => [parent::class, 'zipcode', null],
        'city' => [parent::class, 'city', null],
        'email' => [parent::class, 'email', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'is_confirmed' => [parent::class, 'is_confirmed', null],
        'name' => [parent::class, 'name', null],
        'ope_employe' => [parent::class, 'ope_employe', null],
        'operations' => [parent::class, 'operations', null],
        'password' => [parent::class, 'password', null],
        'phone' => [parent::class, 'phone', null],
        'roles' => [parent::class, 'roles', null],
        'street' => [parent::class, 'street', null],
        'zipcode' => [parent::class, 'zipcode', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
