# config/routes.yaml

controllers:
  resource: '../src/Controller/'
  type: attribute

auth_oauth_check:
  path: /oauth/check/{service}
  controller: App\Controller\OAuthController::authenticate

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

api_adresse_search:
  path: /api/adresse/search
  controller: App\Controller\AdresseApiController::search
  methods: GET
    
accueil:
    path: /
    controller: App\Controller\HomeController::index

services:
    path: /services
    controller: App\Controller\ServicesController::index

equipe:
    path: /equipe
    controller: App\Controller\EquipeController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

recrutement:
    path: /recrutement
    controller: App\Controller\RecrutementController::index

profile_edit:
    path: /profile/edit
    controller: App\Controller\ProfilController::edit

ajax_get_cleaning_options:
    path: /ajax/get-cleaning-options
    controller: App\Controller\AjaxOperationController::getCleaningOptions
    methods: POST

ajax_create_operation:
    path: /ajax/create-operation
    controller: App\Controller\AjaxOperationController::createOperation
    methods: POST

ajax_update_operation:
    path: /ajax/update-operation/{id}
    controller: App\Controller\AjaxOperationController::updateOperation
    methods: POST

operation_edit:
    path: /operation/edit/{id}
    controller: App\Controller\AjaxOperationController::editOperation
    methods: GET

operation_download_invoice:
    path: /operation/download-invoice/{id}
    controller: App\Controller\InvoiceController::downloadInvoice
    methods: GET
    requirements:
        id: '\d+'

check_password:
    path: /check-password
    controller: App\Controller\ProfilController::checkPassword
    methods: POST

ajax_update_operation_operator:
    path: /ajax/update-operation-operator/{id}
    controller: App\Controller\AjaxOperationController::updateOperationOperator
    methods: [POST]
    requirements:
        id: '\d+'

admin_change_operator:
    path: /admin/change-operator/{id}
    controller: App\Controller\AjaxOperationController::changeOperator
    requirements:
        id: '\d+'
