# config/routes.yaml
controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

auth_oauth_check:
  path: oauth/check/{service}
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_adresse_search:
    path: ../src/Controller/
    controller: App\Controller\AdresseApiController::search
    methods: GET
