# config/routes.yaml

controllers:
  resource: '../src/Controller/'
  type: annotation

auth_oauth_check:
  path: /oauth/check/{service}
  controller: App\Controller\OAuthController::authenticate

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

api_adresse_search:
  path: /api/adresse/search
  controller: App\Controller\AdresseApiController::search
  methods: GET

operation_accept:
    path: /operation/{id}/accept
    controller: App\Controller\OperationController::accept

operation_decline:
    path: /operation/{id}/decline
    controller: App\Controller\OperationController::decline
    