parameters:
    app.locales: [fr, en]
    
services:
    _defaults:
        autowire: true      # Injection automatique des dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services en tant que commandes, abonnés d'événements, etc.
        public: false 

    # Configuration de Redis pour la connexion directe
    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                - '%env(REDIS_HOST)%'  # Assurez-vous que cette variable est bien définie dans votre fichier .env
                - '%env(int:REDIS_PORT)%'  # Utilisation de la conversion de type pour le port

    # Configuration de l'adaptateur Redis pour Symfony Cache
    Symfony\Component\Cache\Adapter\RedisAdapter:
        arguments:
            - '@Redis'
            - namespace: '%env(APP_ENV)%_cache_namespace'
            - options: { timeout: 5 }

    # Services liés à la sécurité
    App\Security\OperationVoter:
        tags:
            - { name: 'security.voter' }

    # Abonnés d'événements
    App\EventSubscriber\EasyAdminSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\EventSubscriber\LogoutEventListener:
        arguments:
            $logsService: '@App\Service\LogsService'
        tags:
            - { name: 'kernel.event_subscriber' }

    # Définition des services pour les classes dans src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Security/UserVoter.php'

    # Services spécifiques
    App\Service\InvoiceService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\AjaxOperationController: ~

    App\Service\LogsService:
        arguments:
            $httpClient: '@http_client' 

    App\Twig\AppExtension:
        tags:
            - { name: 'twig.extension' }

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventSubscriber\RegisterEventListener:
        arguments:
            $logsService: '@App\Service\LogsService'
        tags:
            - { name: 'kernel.event_subscriber' }
