<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPKj2jaC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPKj2jaC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPKj2jaC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPKj2jaC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPKj2jaC\App_KernelDevDebugContainer([
    'container.build_hash' => 'PKj2jaC',
    'container.build_id' => '439cdb25',
    'container.build_time' => 1709026330,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPKj2jaC');
