<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYRmxTxo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYRmxTxo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYRmxTxo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYRmxTxo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYRmxTxo\App_KernelDevDebugContainer([
    'container.build_hash' => 'YRmxTxo',
    'container.build_id' => '1a673b86',
    'container.build_time' => 1708509943,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYRmxTxo');
